# Project information
site_name: distilabel
site_url: https://argilla-io.github.io/distilabel
site_author: Argilla, Inc.
site_description: AI Feedback framework

# Repository
repo_name: argilla-io/distilabel
repo_url: https://github.com/argilla-io/distilabel.git

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: assets/distilabel-icon.svg
  favicon: assets/distilabel-icon.svg
  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

watch:
  - src/distilabel

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings

nav:
  - Getting started: index.md
  - Concepts: concepts.md
  - Learn:
    - learn/index.md
    - Tutorials:
      - learn/tutorials/index.md
      - Create a Preference Dataset: learn/tutorials/preference-dataset.md
    - User Guides:
      - Tasks:
        - learn/user-guides/tasks/index.md
        - Create your own task for Question Answering: learn/user-guides/tasks/qa-task.md
      - LLMs: learn/user-guides/create-pipeline.md
      - Pipelines:
        - learn/user-guides/preference-dataset.md
  - Code Reference: reference/
