[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rlxf"
description = "Automatic build of preference datasets for LLM alignment"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = ["llm", "annotation", "alignment"]
authors = [{ name = "Argilla", email = "admin@argilla.io" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["datasets >=2.14.0"]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["black ==23.10.0", "ruff ==0.1.0", "pre-commit >=3.5.0"]
argilla = ["argilla >=1.16.0"]

[project.urls]
Documentation = "https://github.com/argilla/rlxf#readme"
Issues = "https://github.com/argilla/rlxf/issues"
Source = "https://github.com/argilla/rlxf"

[tool.hatch.version]
path = "src/rlxf/__init__.py"

[tool.ruff]
line-length = 88
select = ["E", "W", "F", "I", "C", "B"]
ignore = ["E501", "B905", "B008"]
