[tool.poetry]
name = "rlxf"
version = "0.1.0"
description = "Open-source framework for building preference datasets and models for LLM alignment"
authors = ["Argilla <admin@argilla.io>"]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^1.9.0"
openai = "^0.11.2"
argilla = "^1.16.0"
transformers = "^4.11.3"
datasets = "^1.14.0"

[tool.poetry.dev-dependencies]
# List your project's development dependencies here

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rlxf = "rlxf.cli:main"

[tool.poetry.extras]
dev = ["pytest", "black", "flake8", "mypy"]

[tool.poetry]
name = "rlxf"
version = "0.1.0"
description = "Open-source framework for building preference datasets and models for LLM alignment"
authors = ["Argilla <admin@argilla.io>"]

[tool.poetry.dependencies]
python = "^3.10"
openai = "^0.11.2"
argilla = "^1.16.0"
transformers = "^4.11.3"
datasets = "^1.14.0"

[tool.poetry.dev-dependencies]
# List your project's development dependencies here

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"