[tool.poetry]
name = "rlxf"
version = "0.1.0"
description = "Framework to automatically build preference datasets for LLM alignment"
authors = ["Argilla <admin@argilla.io>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
torch = "^1.13.1"
openai = "^0.28.1"
argilla = "^1.16.0"
transformers = "^4.34.0"
datasets = "^2.14.5"

[tool.poetry.dev-dependencies]
# List your project's development dependencies here

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.25.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
rlxf = "rlxf.cli:main"

[tool.poetry.extras]
dev = ["pytest", "black", "flake8", "mypy"]

